name: container

permissions:
  packages: write

on:
  push:
    branches: [master]

jobs:
  build_and_push:
    strategy:
      matrix:
        # renovate: datasource=github-releases packageName=NLnetLabs/unbound
        unbound_version: [1.24.0]
    runs-on: ubuntu-latest
    env:
      REPOSITORY: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v5

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure tags based on git tags + latest
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REPOSITORY }}
          tags: |
            type=raw,value=${{ matrix.unbound_version }}

      - name: Docker login on main origin
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          sbom: true
          provenance: mode=max
          context: .
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ghcr.io/${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: REPOSITORY=${{ env.REPOSITORY }}
